---
- name: Install NFS client packages
  become: yes
  apt:
    name: "{{ nfs_client_packages }}"
    state: present
    update_cache: yes

- name: Create mount directory
  file:
    path: "{{ nfs_mount_dir }}"
    state: directory

- name: Mount NFS share
  mount:
    path: "{{ nfs_mount_dir }}"
    src: "{{ nfs_server_ip }}:{{ nfs_shared_dir }}"
    fstype: nfs
    opts: rw
    state: mounted
