---
- name: Install dependencies
  apt:
    name: ['curl', 'gnupg2', 'ca-certificates', 'lsb-release']
    update_cache: yes

- name: Add nginx key
  apt_key:
    url: "{{ nginx_key }}"
    state: present
  register: add_nginx_key

- name: Update apt-key cache
  command: /usr/bin/apt-key update
  when: add_nginx_key.changed

- name: Set up nginx repo
  apt_repository:
    repo: "{{ nginx_repo }}"
    state: present
    filename: nginx
    update_cache: yes

- name: Install nginx
  apt:
    name: ['nginx']

- name: Mark nginx as held
  dpkg_selections:
    name: nginx
    selection: hold

- name: Set up nginx  test website
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart nginx

- name: Set up nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: copy index.html
  template:
    src: index.html
    dest: /var/www/html/

- name: Start and enable nginx
  service:
    name: nginx
    enabled: yes
    state: started
