---
- hosts: all
  become: true
  tasks:
    - name: Install nginx
      apt: name=nginx state=latest
    
    - name: starting nginx
      service:
          name: nginx
          state: started
      
    - name: copy the nginx config file and restart nginx
      copy:
        src:  /Users/vishnu/DevOps/ansible/default.conf 
        dest: /etc/nginx/sites-available/default.conf
      
      
    - name: copy the content of the web site
      copy:
        src:  /Users/vishnu/DevOps/ansible/index.html
        dest: /var/www/html/index.html
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
