---
- hosts: ip
  become: true
  tasks:
  - name: Install prerequisites
    apt:  name={{item}} update_cache=yes
    with_items:
     - gnupg2
     - ca-certificates
     - curl
     - lsb-release
  - name:    Add nginx GPG key
    apt_key: url=https://nginx.org/keys/nginx_signing.key
  - name:    Add nginx APT repository
    apt_repository:
      repo: deb http://nginx.org/packages/mainline/ubuntu bionic nginx
  - name:    Install nginx
    apt:     name=nginx update_cache=yes
  
