---
- name: installing ssm agent on all machines
  hosts: localhost
  gather_facts: yes
  become: true

  
  tasks:
    - name: download ssm agent on ubuntu machines
      snap:
        name: amazon-ssm-agent
        state: present
        classic: yes
      when: ansible_os_family == 'Debian'

    - name: start ssm agent on ubuntu machines
      systemd:
        name: snap.amazon-ssm-agent.amazon-ssm-agent.service
        state: started
      when: ansible_os_family == 'Debian'      
    
    - name: download ssm agent on centos machines
      yum:
        name: https://s3.us-east-1.amazonaws.com/amazon-ssm-us-east-1/latest/linux_amd64/amazon-ssm-agent.rpm
        state: present
      when: ansible_os_family == 'RedHat' 

    - name: start ssm agent service  
      service: 
        name: amazon-ssm-agent
        state: started
        enabled: yes
      when: ansible_os_family == 'RedHat'


    
