---
- name: Manage users
  become: yes
  hosts: all
  gather_facts: yes
  pre_tasks:
    - include_role:
        name: pre-tasks
  roles:
    - users
  vars:
    users:
      - username: test
        groups:
          - sudo
        state: disabled
        password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits') }}"
      - username: vishnu
        groups:
          - sudo
        state: disabled
        password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits') }}"
      - username: naresh
        groups:
          - sudo
        state: present
        password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits') }}"
      - username: prakash
        groups:
          - sudo
        state: present
        password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits') }}"
      - username: suraj
        groups:
          - sudo
        state: present
        password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits') }}"
      - username: test2
        groups:
          - sudo
        state: present
        password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits') }}"
