- name: Install Latest Nginx on Remote Server
  hosts: host  # IP address of your remote server
  become: yes
  vars:
    ansible_ssh_user: ubuntu  # Replace with your actual SSH user
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_rsa  # If you're using a private key for SSH authentication

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install prerequisites for adding repositories
      apt:
        name:
          - curl
          - gnupg2
          - ca-certificates
          - lsb-release
          - ubuntu-keyring
        state: present

    - name: Add Nginx signing key
      shell: |
        curl -fsSL https://nginx.org/keys/nginx_signing.key | gpg --dearmor -o /usr/share/keyrings/nginx-archive-keyring.gpg

    - name: Set up Nginx repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" | tee /etc/apt/sources.list.d/nginx.list

    - name: Update APT package cache after adding Nginx repository
      apt:
        update_cache: yes

    - name: Install Latest Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running and enabled on boot
      service:
        name: nginx
        state: started
        enabled: yes
