---
- name: Install NFS server packages
  become: yes
  apt:
    name: "{{ nfs_server_packages }}"
    state: present
    update_cache: yes

- name: Create shared directory
  file:
    path: "{{ nfs_shared_dir }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: '0755'

- name: Configure /etc/exports
  lineinfile:
    path: /etc/exports
    line: "{{ nfs_shared_dir }} {{ nfs_network }}(rw,sync,no_subtree_check)"
    state: present

- name: Restart NFS server
  service:
    name: nfs-kernel-server
    state: restarted
